export type PromptCategory =
  | '短剧叙事'
  | '人物角色'
  | '场景空间'
  | '镜头运动'
  | '光影氛围'
  | '产品广告'
  | '口播带货'
  | '知识自媒体'
  | '转场特效'
  | '风格质感'

export interface PromptItem {
  id: string
  title: string
  prompt: string
  promptZh: string
  category: PromptCategory
  tags: string[]
  useCount: number
  isFavorited: boolean
  isCustom: boolean
  createdAt: string
}

export const mockPrompts: PromptItem[] = [
  {
    id: 'p1',
    title: '短剧爆点开场 3 秒钩子',
    prompt: 'Vertical 9:16 AI short drama, cold open hook in first 3 seconds, a young founder receives a shocking phone call, tense close-up, fast push-in, dramatic pause, Chinese urban night, cinematic contrast lighting, subtitle-safe framing, high emotional tension',
    promptZh: '适合短剧第一幕开场。核心目标是前 3 秒制造冲突和悬念，用电话、消息、门被推开等事件直接切入，适配竖屏短剧投流。',
    category: '短剧叙事',
    tags: ['短剧开场', '3秒钩子', '竖屏', '冲突'],
    useCount: 8421,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p2',
    title: '短剧情绪对峙双人戏',
    prompt: 'Two-character confrontation scene, vertical frame, one standing one sitting, silent pressure, alternating over-the-shoulder shots, micro facial expressions, restrained anger, realistic office interior, cinematic drama blocking, shallow depth of field, premium streaming series look',
    promptZh: '适合老板与员工、情侣、母女、合伙人冲突戏。强调表情细节、空间压迫感和对话停顿，适合做情绪张力拉满的中段戏。',
    category: '短剧叙事',
    tags: ['双人戏', '对峙', '表情细节', '情绪张力'],
    useCount: 6912,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p3',
    title: '短剧反转结尾定格',
    prompt: 'Final reveal in AI mini drama, protagonist turns back slowly, hidden truth exposed, extreme close-up on eyes, 0.5 second hold before cut, dramatic rim light, dark corridor, emotionally devastating ending, viral cliffhanger style, vertical 9:16',
    promptZh: '用于短剧结尾反转或卡点断更。重点在“回头”“停顿”“真相暴露”“眼神特写”，利于引导下一集追更。',
    category: '短剧叙事',
    tags: ['反转', '卡点', '结尾', '追更'],
    useCount: 7280,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p4',
    title: '高颜值女主近景',
    prompt: 'Beautiful female lead, natural Chinese features, expressive eyes, subtle makeup, premium skin texture, vertical close portrait, confident but fragile emotion, realistic lighting, high-end AI drama heroine design, cinematic beauty shot',
    promptZh: '适合短剧女主、情感号、口播人设统一。重点是五官稳定、皮肤质感干净、情绪带故事感，方便连续生成统一角色。',
    category: '人物角色',
    tags: ['女主', '人设统一', '近景', '角色设定'],
    useCount: 6034,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p5',
    title: '精英总裁男主设定',
    prompt: 'Male CEO character design, 30 years old, sharp suit, controlled expression, expensive watch, clean hairstyle, corporate authority, luxury office environment, dramatic side light, premium short drama male lead, highly consistent identity',
    promptZh: '适合霸总、创业者、老板人设。强调服装、年龄、发型、配饰和权威感，适合连续剧情和企业品牌内容统一角色输出。',
    category: '人物角色',
    tags: ['男主', '总裁', '霸总', '角色稳定'],
    useCount: 5771,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p6',
    title: '家庭客厅温暖冲突场',
    prompt: 'Chinese family living room, warm ambient lighting, sofa and dining table in same frame, realistic modern apartment, evening atmosphere, emotional domestic drama staging, clear foreground midground background layers, vertical composition for short drama',
    promptZh: '适合婆媳、夫妻、亲子、返乡等剧情。要点是空间真实、层次清晰、光线温暖但带冲突感，方便人物调度。',
    category: '场景空间',
    tags: ['家庭场景', '客厅', '亲情', '生活化'],
    useCount: 5204,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p7',
    title: '高级写字楼谈判空间',
    prompt: 'Modern glass office, luxury meeting room, city skyline outside, deep perspective lines, polished table reflection, restrained corporate palette, premium business drama environment, vertical 9:16 safe composition, realistic Chinese metropolis',
    promptZh: '适合商务谈判、融资、甲乙方、职场短剧和品牌片。空间要显得贵、冷、压迫，带都市精英感。',
    category: '场景空间',
    tags: ['办公室', '商务', '谈判', '都市'],
    useCount: 4582,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p8',
    title: '稳定推镜主角出场',
    prompt: 'Slow cinematic push-in toward protagonist, subject centered, confident entrance, subtle background motion, premium depth, smooth dolly move, vertical short-form video composition, dramatic anticipation, commercial grade camera language',
    promptZh: '适合人物第一次亮相、口播主讲人出场、产品主视觉抬升。核心是稳、准、强气场。',
    category: '镜头运动',
    tags: ['推镜', '人物出场', '稳镜头', '主角'],
    useCount: 7420,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p9',
    title: '手持追随纪实感',
    prompt: 'Handheld follow shot, realistic micro shake, walking with subject through corridor, immersive point-of-view energy, documentary urgency, dynamic framing, social-media native realism, vertical mobile-first storytelling',
    promptZh: '适合追人、赶路、突发事件、探店和资讯号。手持追随能显著提升真实感和代入感。',
    category: '镜头运动',
    tags: ['手持', '追随', '纪实感', '代入'],
    useCount: 4873,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p10',
    title: '主体环绕展示镜头',
    prompt: 'Orbit camera around subject, 180-degree circular motion, hero object stays sharp, elegant parallax, premium reveal shot, ad-level product presentation, dramatic spotlight and floating particles',
    promptZh: '适合产品发布、人物定场、关键道具揭示。常用于高价值感镜头和广告级展示。',
    category: '镜头运动',
    tags: ['环绕', '展示', '英雄镜头', '产品'],
    useCount: 5541,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p11',
    title: '夜雨霓虹情绪光',
    prompt: 'Rainy night, neon reflections on wet street, cinematic blue and magenta contrast, lonely emotional atmosphere, shallow depth, dramatic backlight, premium short drama mood frame, mist and light haze',
    promptZh: '适合失恋、复仇、孤独、城市情绪向内容。夜雨加霓虹是短剧里最稳定的情绪放大器。',
    category: '光影氛围',
    tags: ['夜雨', '霓虹', '情绪光', '都市'],
    useCount: 6318,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p12',
    title: '晨光治愈生活氛围',
    prompt: 'Warm morning sunlight through window, clean room, dust particles in light beam, peaceful domestic mood, soft shadows, healing lifestyle video aesthetic, cozy realistic colors, vertical composition',
    promptZh: '适合治愈号、家居号、母婴号、生活方式内容。重点在干净、透气、让人想停留。',
    category: '光影氛围',
    tags: ['晨光', '治愈', '生活方式', '温暖'],
    useCount: 4127,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p13',
    title: '电商产品英雄特写',
    prompt: 'Hero product shot, luxury commercial style, clean background, controlled reflections, premium macro detail, dramatic lighting, floating particles, high conversion ad visual, vertical 9:16 for feed ads',
    promptZh: '适合护肤、美妆、3C、小家电、电商详情前 5 秒。重点是把产品拍得值钱、可信、想点进。',
    category: '产品广告',
    tags: ['产品广告', '英雄特写', '电商', '高转化'],
    useCount: 9034,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p14',
    title: '开箱种草节奏模板',
    prompt: 'Fast-paced unboxing video, clean desk setup, hands interact with product, satisfying sound cues implied, quick detail cut-ins, lifestyle influencer aesthetic, trust-building social commerce style, vertical short video',
    promptZh: '适合自媒体种草、达人开箱、品牌新品首发。强调手部互动、细节切镜和“这东西真想买”的感觉。',
    category: '产品广告',
    tags: ['开箱', '种草', '达人', '新品'],
    useCount: 6880,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p15',
    title: '口播带货高信任人设',
    prompt: 'Talking-head sales video, direct eye contact, confident Chinese host, clean studio background, clear product in hand, persuasive but natural delivery, high trust conversion style, vertical 9:16, subtitle-safe framing, social commerce native',
    promptZh: '适合 AI 口播带货、品牌主理人出镜、直播切片。重点是信任感、稳定人设、拿货展示和转化气质。',
    category: '口播带货',
    tags: ['口播', '带货', '高信任', '转化'],
    useCount: 9712,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p16',
    title: '探店推荐口播模板',
    prompt: 'Vertical city food review video, host walks into store, energetic but authentic recommendation tone, quick venue cutaways, signature dish close-ups, localized atmosphere, social proof style, perfect for short-form recommendation content',
    promptZh: '适合探店、餐饮推广、本地生活号。结构上是进店一句钩子 + 环境 + 菜品 + 结论，转化效率高。',
    category: '口播带货',
    tags: ['探店', '本地生活', '推荐', '餐饮'],
    useCount: 6445,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p17',
    title: '知识号专家讲解镜头',
    prompt: 'Expert explainer video, clean frontal composition, clear gestures, educational authority, simple modern background, calm but engaging delivery, vertical knowledge-content format, trustworthy media host style',
    promptZh: '适合财经、法律、职场、教育、健康科普等知识类账号。重点是“像专家，但不端着”，让用户愿意看完。',
    category: '知识自媒体',
    tags: ['知识号', '专家', '讲解', '自媒体'],
    useCount: 7811,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p18',
    title: '新闻资讯快节奏播报',
    prompt: 'Breaking-news style vertical video, anchor-led delivery, bold framing, quick cut visual support, data callout areas, urgency without chaos, mobile-first information packaging, short-form current affairs explainer',
    promptZh: '适合资讯号、行业快讯、热点点评。要求画面利落、信息密度高、镜头和文案节奏同步。',
    category: '知识自媒体',
    tags: ['资讯号', '快讯', '播报', '热点'],
    useCount: 5366,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p19',
    title: '卡点闪白转场',
    prompt: 'Impact transition, flash frame, whip pan into next shot, beat-synced editing feel, kinetic energy, social-video native transition language, keeps subject continuity while increasing pace',
    promptZh: '适合混剪、产品展示、情绪转折和高潮推进。闪白和 whip pan 是短视频里最常用的高效转场组合。',
    category: '转场特效',
    tags: ['转场', '卡点', '闪白', '混剪'],
    useCount: 4738,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p20',
    title: '烟雾粒子高能揭示',
    prompt: 'Cinematic reveal with smoke, dust, floating particles, strong contrast spotlight, object emerges from darkness, premium teaser style, suspenseful energy, perfect for title reveal or product launch moment',
    promptZh: '适合新品发布、角色登场、片名揭示、课程包装。重点是把“出现”做得有仪式感。',
    category: '转场特效',
    tags: ['揭示', '烟雾', '粒子', '高能'],
    useCount: 3894,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p21',
    title: '高级电影质感胶片风',
    prompt: 'Cinematic film texture, subtle grain, natural skin tones, soft highlight roll-off, premium drama color grading, emotionally rich contrast, grounded realism, not over-stylized, streaming-platform quality',
    promptZh: '适合品牌短剧、剧情广告、人物故事片。核心不是花，而是“像真片”。',
    category: '风格质感',
    tags: ['胶片', '电影感', '质感', '高级'],
    useCount: 8274,
    isFavorited: true,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p22',
    title: '国风意境写意风格',
    prompt: 'Chinese aesthetic video style, elegant brush-inspired composition, restrained colors, poetic atmosphere, flowing fabric, subtle wind motion, premium oriental visual storytelling, refined and artistic',
    promptZh: '适合国风品牌、文旅、文化内容、情绪短片。要点是克制留白，不要做成廉价古风滤镜。',
    category: '风格质感',
    tags: ['国风', '意境', '文旅', '高级审美'],
    useCount: 4622,
    isFavorited: false,
    isCustom: false,
    createdAt: '2026-03-16',
  },
  {
    id: 'p23',
    title: '我的自定义模板：AI 短剧招商口播',
    prompt: 'Vertical founder talking-head video for AI short drama business, persuasive B2B tone, explain fast production pipeline, show case-study inserts, emphasize scalable content output, premium startup brand image, trustworthy and efficient',
    promptZh: '这是结合你们业务预置的模板，适合招商、加盟、客户合作介绍，突出 AI 短剧能力和自媒体视频批量生产能力。',
    category: '口播带货',
    tags: ['招商', 'AI短剧', 'B2B', '品牌介绍'],
    useCount: 63,
    isFavorited: true,
    isCustom: true,
    createdAt: '2026-03-16',
  },
  {
    id: 'p24',
    title: '我的自定义模板：批量自媒体视频工厂',
    prompt: 'Fast-turnaround AI media content pipeline visual, multiple vertical video frames, clean dashboard aesthetic, content factory metaphor, efficient automation, creator economy, scalable short-form output, suitable for SaaS landing page or brand promo',
    promptZh: '这是结合你们“AI 快速生成自媒体视频”业务做的品牌化提示词，适合官网、宣传片、方案介绍页和销售素材。',
    category: '产品广告',
    tags: ['自媒体工厂', '自动化', 'SaaS', '品牌视觉'],
    useCount: 38,
    isFavorited: false,
    isCustom: true,
    createdAt: '2026-03-16',
  },
]
